Feat: Create chip component
Covigator/Covigator-FE pull request #11
Opened 2024-07-20 15:39 UTC by crohasang

## 요약

이슈 번호 : COV-42

## 변경 사항
Chip component 생성

## 리뷰 요구사항
components/common/chip에 Chip.tsx와 Chip.types.ts를 생성했습니다.
(해당 브랜치는 COV-29-COMMON-COMPONENT를 base로 생성했습니다.)

## 확인 방법 (선택)

<br/>

---

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

    * P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
    * P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
    * P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-07-22 00:10 UTC, hyunn522 requested changes
고생하셨어요!! 최고!!
리뷰 남긴 것만 확인 부탁드려요

2024-07-22 00:10 UTC, hyunn522 commented on src/components/common/chip/Chip.tsx
> +const Chip: React.FC<ChipProps> = ({
p2: React.FC를 쓰시는 이유가 있을까요? 전 사용해본 적이 없어 알아보다가 관련 레퍼런스를 발견해서 공유드립니닷
혹시 틀린 게 있다면 말씀해주세요!!
https://yceffort.kr/2022/03/dont-use-react-fc#reactfc%EB%8A%94-defaultprops%EB%A5%BC-%EC%93%B0%EC%A7%80-%EB%AA%BB%ED%95%98%EA%B2%8C-%EB%A7%8C%EB%93%A0%EB%8B%A4

2024-07-22 00:10 UTC, hyunn522 commented on src/components/common/chip/Chip.types.ts
> +};
p2: 현재 base style에는 size나 state 관련 속성이 없으니, 이처럼 props로 반드시 넘겨줘야 하는 속성은 옵셔널 체이닝을 빼는 건 어떨까요?
(아예 빼기 애매하다면 style을 지정할 때 기본값을 설정해주면 좋을 것 같아요
`size ? styles.size[size] ? 'sm'` 이런 식으로요)

2024-07-22 05:12 UTC, crohasang commented on src/components/common/chip/Chip.tsx
> +const Chip: React.FC<ChipProps> = ({
저는 함수형 컴포넌트 생성할 때 아래와 같이 생성했었습니다.
![image](https://github.com/user-attachments/assets/b73a8bde-d214-421e-b717-b4cf43df168d)

**React.FC 사용 시 문제점**
1. React.FC를 사용하면 props에 기본적으로 children이 들어간다.
-> children의 타입 지정 없이 전달 가능

2. defaultProps 사용 이슈
-> 최근 테스트 결과로는 사용 가능하다는 글도 있네요

3. 제네릭 문법 미지원

개인적인 생각으로는 사용해도 크게 상관은 없을 것 같은데 React.FC 사용을 지양하라는 글들을 보고 아무래도 바꾸면 좋겠다는 생각이 들었습니다. 나중에 다른 브랜치에서 수정할까 생각 중입니다!


출처1: https://shape-coding.tistory.com/entry/TypeScript-ReactFC%EC%97%90-%EC%82%AC%EC%9A%A9%EC%97%90-%EB%8C%80%ED%95%B4-%EC%83%9D%EA%B0%81%ED%95%B4%EB%B3%B4%EA%B8%B0

출처2: https://velog.io/@yena1025/FunctionComponent-FC-%EC%82%AC%EC%9A%A9-%EC%A4%84%EC%9D%B4%EA%B8%B0-24jhm0wp

함수형 컾

2024-07-22 05:13 UTC, crohasang commented on src/components/common/chip/Chip.types.ts
> +};
다시 살펴보니 무조건 prop으로 넘겨져야 하므로 옵셔널 체이닝 빼는 게 맞는 것 같습니다!!

2024-07-22 06:31 UTC, hyunn522 commented on src/components/common/chip/Chip.tsx
> +const Chip: React.FC<ChipProps> = ({
네 좋습니다! 덕분에 저도 새롭게 알게 됐네요~

2024-07-24 06:08 UTC, crohasang commented on src/components/common/chip/Chip.types.ts
> +};
반영 완료해서 push했습니다!

2024-07-25 12:19 UTC, hyunn522 approved these changes
굿!!

2024-07-25 12:22 UTC, merged