Feat: Create Dialog component
Covigator/Covigator-FE pull request #12
Opened 2024-07-20 16:55 UTC by crohasang

## 요약

이슈 번호 : COV-41

## 변경 사항
components/common에 dialog 폴더를 만들고 Dialog.tsx와 Dialog.types.ts를 생성해서 Dialog component를 구현했습니다.
![image](https://github.com/user-attachments/assets/cb9e7ad2-859e-43d4-9d59-610084f5d459)

## 리뷰 요구사항

## 확인 방법 (선택)

<br/>

---

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

    * P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
    * P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
    * P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-07-23 04:14 UTC, hyunn522 requested changes
수고하셨습니다~~ 잘 뜨는 거 확인했고, 스타일 및 props 관련해서 코멘트 단 거 확인 부탁드려요
추가로, context API를 활용해서 모달 관리하면 모달 열렸을 때 상태 및 배경 관련해서 괜찮았던 기억이 나서 레퍼런스 남깁니다
 리팩토링하는 게 좋을 것 같긴 한데, 의견 부탁드립니닷
https://leego.tistory.com/entry/React-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9C%BC%EB%A1%9C-%EB%AA%A8%EB%8B%AC-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

2024-07-23 04:14 UTC, hyunn522 commented on src/components/common/dialog/Dialog.types.ts
> +  title?: string;
p2: 필수 항목이라 옵셔널 체이닝 빼는 게 좋을 것 같습니다!

2024-07-23 04:14 UTC, hyunn522 commented on src/components/common/dialog/Dialog.tsx
> +          <h3 className="text-[18px] leading-[26px] text-center text-bk-100">
p3: 디자인시스템 적용해주세요!

2024-07-23 04:14 UTC, hyunn522 commented on src/components/common/dialog/Dialog.tsx
> +          className="bg-sub-300 border rounded-xl font-semibold"
p2: 기존 버튼 컴포넌트에서 정의해놓은 스타일이나 props로 제어할 수 있는 부분이 아닌가요?? border는 피그마상으로 확인되지 않고, font 및 bg는 버튼 컴포넌트에 커스텀되어있는 것 같아서요~

2024-07-24 06:02 UTC, crohasang commented
![image](https://github.com/user-attachments/assets/08253af7-6bed-4822-ad8f-ce098d0ae4e4)

1. src에서 context 폴더를 생성하고 ModalProvider.tsx를 생성했습니다.
2. src에서 hooks 폴더를 생성하고 useModal.tsx를 생성했습니다.
3. src/types에 modal.ts를 생성했습니다.
4. Dialog 컴포넌트에 위에 언급한 context와 hook을 적용했습니다.
5. button 컴포넌트에 'sub-300' color 요소를 추가했습니다.
6. src/pages/Test에 Hasang.tsx 페이지를 생성하였고, 해당 페이지에 Dialog를 테스트했습니다.(이미지 위에 첨부)
7. Dialog 컴포넌트에서 디자인 시스템이 적용되지 않은 곳에 디자인 시스템을 적용했습니다.

2024-07-24 06:04 UTC, crohasang commented
> 수고하셨습니다~~ 잘 뜨는 거 확인했고, 스타일 및 props 관련해서 코멘트 단 거 확인 부탁드려요 추가로, context API를 활용해서 모달 관리하면 모달 열렸을 때 상태 및 배경 관련해서 괜찮았던 기억이 나서 레퍼런스 남깁니다 리팩토링하는 게 좋을 것 같긴 한데, 의견 부탁드립니닷 https://leego.tistory.com/entry/React-%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9C%BC%EB%A1%9C-%EB%AA%A8%EB%8B%AC-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

해당 레퍼런스에서 Context API를 활용하여 Modal을 구현하는 법을 활용하여 Modal을 제어하는 코드를 구현하였습니다! 코드 한 번 살펴봐주시면 감사합니다

2024-07-26 08:52 UTC, hyunn522 approved these changes
리뷰가 늦어서 죄송합니다ㅜㅜ
너무 수고하셨습니다!!! 모달 열려있을 때 배경 제어하는 부분 관해서도 있으면 좋을 것 같은데,
일단 머지하고 생각해봅시닷
(https://github.com/Kusitms-29th-Meetup-TeamE/Frontend/pull/6
이 링크 참고해도 좋을 것 같습니다)

2024-07-26 08:52 UTC, hyunn522 commented on src/context/ModalProvider.tsx
> +  children: ReactNode;
p3: 오 인터페이스로 래핑한 부분 유연성 측면에서 좋은 것 같아요!

2024-07-26 08:52 UTC, hyunn522 commented on src/hooks/useModal.tsx
> +  }: Omit<ModalState, 'props'> & { props?: any }) => {
p3: any 타입은 지양하는 게 좋을 것 같아요 lint에도 잡히네요 ㅜㅜ

2024-07-26 08:52 UTC, hyunn522 commented on src/components/common/dialog/Dialog.tsx
> +    onCancel();
p3: 취소 버튼은 눌렀을 때 closeModal 외의 처리를 해줄 일이 현재 저희 플로우 상으론 없을 것 같은데, onCancel은 props에서 제외해서 가볍게 가는 건 어떨까요?

2024-07-26 08:52 UTC, hyunn522 commented on src/pages/Test/Hasang.tsx
p3: 테스트 넘넘 좋습니다!!

2024-07-26 12:00 UTC, merged