Feat: Create login, register, find/id, find/password view
Covigator/Covigator-FE pull request #16
Opened 2024-07-30 11:14 UTC by crohasang

## 요약

이슈 번호 : #COV-45

## 변경 사항
1. 로그인 화면을 구현했습니다.
![image](https://github.com/user-attachments/assets/e706d6ce-f350-447a-a9f9-ec73a6b6f8e1)
<br><br>

2. 회원가입 화면을 구현했습니다.
(닉네임, 이름, 아이디, 비밀번호, 비밀번호 확인에 내용이 입력되있고 비밀번호와 비밀번호 확인에 입력된 번호가 같으면
'입력하기' 버튼이 활성화됩니다.)<br>

![image](https://github.com/user-attachments/assets/15d4e676-8ba8-4d8b-9735-d45788cc418e)
<br><br>

4. 아이디(이메일) 찾기 화면을 구현했습니다.(아직 상태는 미구현입니다)
![image](https://github.com/user-attachments/assets/38314dfb-58eb-4a79-b186-da11790fea27)
<br><br>

5. 비밀번호 찾기 화면을 구현했습니다.(아직 상태는 미구현입니다)
![image](https://github.com/user-attachments/assets/9d32e83c-83f2-4111-9f81-17c7c615f286)

## 리뷰 요구사항

## 확인 방법 (선택)

<br/>

---

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

    * P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
    * P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
    * P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-07-31 11:40 UTC, hyunn522 requested changes
고생하셨습니다!
gap이나 typo 등의 이슈가 좀 있어서 코멘트 달아놓았습니다 꼭 확인 부탁드립니다~
w-screen, h-screen 부분은 코멘트 단 부분 뿐 아니라
전체적으로 한 번 체크해주시면 좋을 것 같아요
바텀내비가 원랜 없어야 하는 화면이라 처리가 필요할 것 같습니다
(제가 올린 pr에서 path url로 판단하는 부분 추가해놓았는데
해당 부분 보시고 더 좋은 아이디어가 있으면 말씀해주세요)
로그인 화면에서 Input width는 제가 컴포넌트 만들 때 빼먹은 설정이 있어서
추가하고 커밋했습니다 풀 받으시고 작업해주세요!

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Login/index.tsx
> +      <div className="text-sm mt-3 mb-5">
p1: 정의된 typo로 변경 필요할 것 같습니다

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Login/index.tsx
> +        <div className="flex flex-col items-center gap-y-4">
p1: 이 부분 gap이랑 아래 로그인 버튼이랑 이메일 찾기 부분에서의 margin들 피그마랑 동일하게 부탁드립니다

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Login/index.tsx
> +            아이디(이메일) 찾기
p3: ux writing `이메일 찾기`로 변경 부탁드려요

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Login/index.tsx
> +        <div className="flex justify-center mb-28">
p2: 전체 div가 h-screen이라 margin-bottom을 주면 불필요한 스크롤이 생길 수도 있어서, margin-bottom 제거해주시면 좋을 것 같아요~
h-screen 제거한다고 하여도, margin-top 속성을 주는 게 반응형에서 더 알맞게 작동할 것 같습니다

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Login/index.tsx
> +    <div className="w-screen h-screen overflow-x-hidden">
p2: div로 한 번 더 래핑하신 이유가 있을까요?? w-screen, h-screen은 가로 스크롤이 생길 수 있어서 w-full, h-full을 쓰는 게 좋을 것 같아요

2024-07-31 11:40 UTC, hyunn522 commented on src/router.tsx
> +        <Route path="/register" element={<Register />} />
p2: 회원가입 경로로 좀 더 직관적인 `/signup`은 어떨까요?

2024-07-31 11:40 UTC, hyunn522 commented on src/router.tsx
> +import FindId from './pages/Find/Id';
p2: Find 디렉토리 자체를 Login 디렉토리 내부로 옮기면 폴더 구조가 더 직관적일 것 같아요

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Find/Id/index.tsx
> +            <Button size="sm" shape="square" color="sub_300">
p1: button 컴포넌트에 typo 설정이 빠져있는 것 같아요
추가 부탁드립니다!

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Find/Id/index.tsx
> +          <div className="text-body6 text-bk-70">
p2: 피그마에서 Input과의 위치 확인 부탁드립니다

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Register/index.tsx
> +    <div className="w-screen h-screen overflow-x-hidden mt-24">
p1: margin-top 피그마랑 다른 것 같은데 확인 부탁드립니다

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Register/index.tsx
> +      <div className="flex-1 pt-4">
p1: padding-top 중복으로 들어간 것 같아요! 그리고 이 div로 래핑하지 않아도 될 것 같습니다

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Register/index.tsx
> +          <div className="mt-3 mb-6">
p1: 프로필 사진 div와의 gap 한 번 체크해주세요

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Register/index.tsx
> +          <div className="flex flex-col items-center gap-y-3 w-[280px]">
p2: 이미 본문 전체에 양쪽 margin이 들어가있어서, w-full을 주면 반응형 구현에도 알맞으면서 피그마와 같은 환경에서는 280px로 보일 것 같아요

2024-07-31 11:40 UTC, hyunn522 commented on src/pages/Register/index.tsx
> +          <div className="relative flex items-center w-full mt-8 mb-4">
p1: margin 확인 부탁드립니다

2024-07-31 12:31 UTC, crohasang commented on src/pages/Login/index.tsx
> +        <div className="flex justify-center mb-28">
margin-bottom을 주지 않으면 PC 화면에서 '카카오톡 로그인'이 보여서 그랬습니다!

2024-07-31 12:31 UTC, crohasang commented on src/pages/Login/index.tsx
> +      <div className="text-sm mt-3 mb-5">
변경했습니다!

2024-07-31 12:32 UTC, crohasang commented on src/pages/Login/index.tsx
> +        <div className="flex flex-col items-center gap-y-4">
변경했습니다!

2024-07-31 12:32 UTC, crohasang commented on src/pages/Login/index.tsx
> +            아이디(이메일) 찾기
변경했습니다!

2024-07-31 12:47 UTC, crohasang commented on src/pages/Login/index.tsx
> +        <div className="flex justify-center mb-28">
하지만 BottomNavigation은 사라질 예정이므로 바꾸는게 맞는 것 같습니다(사라지면 보일 것이므로). margin-bottom 속성 제거했습니다.

2024-07-31 12:54 UTC, crohasang commented on src/pages/Login/index.tsx
> +    <div className="w-screen h-screen overflow-x-hidden">
w-screen과 h-screen은 w-full과 h-full로 수정했습니다!

div로 한 번 더 래핑한 이유는 그냥 div 하나에 'flex flex-col items-center'를 주면 화면 가운데로 제대로 오지 않아서 그랬습니다.

2024-07-31 14:10 UTC, crohasang commented on src/router.tsx
> +        <Route path="/register" element={<Register />} />
path는 "/signup"으로, 컴포넌트는 <SignUp /> 으로 수정했습니다!

2024-07-31 14:11 UTC, crohasang commented on src/router.tsx
> +import FindId from './pages/Find/Id';
![image](https://github.com/user-attachments/assets/a47508a3-17f3-47eb-9be6-04306d6d3d78)

직접 옮기는 건 안되서 직접 생성해서 옮겨줬습니다!

2024-07-31 14:11 UTC, crohasang commented on src/pages/Find/Id/index.tsx
> +            <Button size="sm" shape="square" color="sub_300">
text-btn2 속성 추가해줬습니다!(Find/Password에서도 적용했습니다)

2024-07-31 14:12 UTC, crohasang commented on src/pages/Find/Id/index.tsx
> +          <div className="text-body6 text-bk-70">
밑의 Input에 mt-[11px] 적용했습니다!

2024-07-31 14:12 UTC, crohasang commented on src/pages/Register/index.tsx
> +    <div className="w-screen h-screen overflow-x-hidden mt-24">
TopBar 밑의 div에 margin-top 올바르게 적용했습니다!

2024-07-31 14:12 UTC, crohasang commented on src/pages/Register/index.tsx
> +      <div className="flex-1 pt-4">
해당 div 삭제해도 괜찮을 것 같아서 삭제했습니다!

2024-07-31 14:14 UTC, crohasang commented on src/pages/Register/index.tsx
> +          <div className="mt-3 mb-6">
프로필 사진 div와의 margin은 맞고, margin-bottom 수정해줬습니다!

2024-07-31 14:14 UTC, crohasang commented on src/pages/Register/index.tsx
> +          <div className="flex flex-col items-center gap-y-3 w-[280px]">
w-full로 바꾸고, Input들을 감싸고 있던 div들을 제거해줬습니다!

2024-07-31 14:15 UTC, crohasang commented on src/pages/Register/index.tsx
> +          <div className="relative flex items-center w-full mt-8 mb-4">
relative를 없애고 margin을 비롯한 css 속성들을 피그마에 맞게 수정해줬습니다!

2024-08-01 09:52 UTC, hyunn522 approved these changes
수정사항 많으셨을 텐데 고생하셨습니다~
피그마랑 최종적으로 확인 후 pr 올려주시면 수정사항이 훨씬 줄어들 것 같습니다
css 파일 관련 답변 부탁드리고 버튼 이슈만 해결되면 바로 머지하면 될 것 같아요!
-> 버튼 관련 이슈는 제 브랜치에서 작업하고 푸쉬하겠습니다 css 파일 관련 답변만 부탁드려요

2024-08-01 09:52 UTC, hyunn522 commented on src/pages/Login/index.tsx
> +            className="text-btn1"
p1: 아 버튼 컴포넌트 자체에 size에 따른 폰트 설정을 말씀드린 거예요!
피그마에 따르면 lg는 Btn1, md와 sm은 Btn2, xs은 Btn3으로 되어있네요

2024-08-01 09:52 UTC, hyunn522 commented on src/components/home/selectBox/SelectBox.css
p1: .css 파일을 추가하신 이유가 있을까요?

2024-08-01 11:45 UTC, crohasang commented on src/pages/Login/index.tsx
> +            className="text-btn1"
아 제가 착각했었네요. 작업 감사합니다!

2024-08-01 11:48 UTC, crohasang commented on src/components/home/selectBox/SelectBox.css
사실 제가 코스 추천 페이지 브랜치(COV-49)에서 해당 파일 작업 중인데, 여기 브랜치에도 css 파일이 push가 되어있네요?? 그래서 삭제하고 push했습니다!

2024-08-01 11:49 UTC, merged