Fix: fix signup and login (local, not kakao)
Covigator/Covigator-FE pull request #31
Opened 2024-09-23 06:02 UTC by crohasang

## 요약

이슈 번호 : #58

## 변경 사항
1. 로컬 회원가입이 정상적으로 처리됩니다.
2. 로컬 로그인이 정상적으로 처리됩니다.
3. 카카오 회원가입, 로그인은 백엔드와의 협의가 필요해보여서 추후 수정 예정입니다.

## 리뷰 요구사항

## 확인 방법 (선택)

1. 회원가입

https://github.com/user-attachments/assets/f3e468d8-7735-4c27-9363-dc9eb0f10894

2. 로그인

https://github.com/user-attachments/assets/5959adcc-bd45-49ff-a622-edfb70a3ac92

<br/>

---

### 📌 PR 진행 시 이러한 점들을 참고해 주세요

    * P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
    * P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
    * P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-09-23 10:47 UTC, hyunn522 requested changes
수고하셨습니다 코멘트 확인 한번만 부탁드려요~

2024-09-23 10:47 UTC, hyunn522 commented on index.html
> +      src="//dapi.kakao.com/v2/maps/sdk.js?appkey=%VITE_KAKAO_REST_API_KEY%&autoload=false"
p3: 이부분 수정 전으로 원복해주셔야 할 것 같아요

2024-09-23 10:47 UTC, hyunn522 commented on src/api/auth.ts
> +      return response.data.access_token;
p2: 토큰이 있다면 바로 localstorage에 저장하고 성공 응답을 반환하는 건 어떨까요?

2024-09-23 10:47 UTC, hyunn522 commented on src/components/login/KakaoLogin.tsx
> +    const handleKakaoCallback = async () => {
p2: 이 함수는 없애도 될 것 같아요

2024-09-26 22:16 UTC, crohasang commented on index.html
> +      src="//dapi.kakao.com/v2/maps/sdk.js?appkey=%VITE_KAKAO_REST_API_KEY%&autoload=false"
넵 원복했습니다!

2024-09-26 22:17 UTC, crohasang commented on src/components/login/KakaoLogin.tsx
> +    const handleKakaoCallback = async () => {
인가코드 처리를 백엔드에서 하니까 없애도 될 것 같습니다. 삭제했습니다!

2024-09-26 22:17 UTC, crohasang commented on src/api/auth.ts
> +      return response.data.access_token;
토큰을 localStorage에 저장하는 과정을 추가했습니다!

2024-09-27 01:02 UTC, merged